source ~/.vim/scripts/plug.vim
source ~/.vim/scripts/common.vim
source ~/.vim/scripts/nerdtree.vim
source ~/.vim/scripts/tagbar.vim
source ~/.vim/scripts/hotkey.vim
source ~/.vim/scripts/airline.vim
source ~/.vim/scripts/vim.vim
source ~/.vim/scripts/python.vim
source ~/.vim/scripts/ansible.vim
source ~/.vim/scripts/go.vim
source ~/.vim/scripts/rust.vim
source ~/.vim/scripts/sql.vim


if filereadable(glob("./.vimrc.local"))
  source ./.vimrc.local
endif
